### ISSUE TITLE
Tell users when they don't have ratings stored for the current version of a category on an event.

### ISSUE THREAD

**Issue by john-andrews12** [SCCapstone/decision_maker#533]
This should be clear on the event details (This will require updating the user choice ratings mapping).

```
The user category ratings map will need to be updated to this structure:
{
  "categoryId": {
    "version": #,
    "ratings": {
      "choiceId": #,
      ...
    }
  },
  ...
}
```

Using the new version data we can alert the user if they don't have up to date ratings saved for a category.

**Comment by joshrap67** [comment]
Implemented in (https://github.com/SCCapstone/decision_maker/pull/573)
