### ISSUE TITLE
Add a blocked list

### ISSUE THREAD

**Issue by joshrap67** [SCCapstone/decision_maker#552]
If a user is on your blocked list, they will no longer be able to add you to any groups. Also removes you from their favorites. This won't remove you from any current groups though.

This might not be necessary I just think it'd be nice to have in case some donut gets a long list of usernames and just starts to spam accounts with new groups. Could also cover our asses legally if someone has someone that is harassing them.

**Comment by john-andrews12** [comment]
Converted to backlog card in projects
