### ISSUE TITLE
Add recurring events

### ISSUE THREAD

**Issue by joshrap67** [SCCapstone/decision_maker#553]
An option for recurring events where the user specifies the days of the week for the event to recur on and the time on each of these days. 

Users would be able to mute recurring events, and see when new choices are selected for the recurring event (similar to how we do it with normal events, just put an exclamation mark there).

On the frontend, this would actually be pretty easy to display recurring events. Similar to the "Groups Home" and "Groups Left" tab, there would be a "Event" tab and "Recurring Events" tab in the groups page. On the recurring events tab, we could have it designed like this:
<img width="269" alt="Untitled" src="https://user-images.githubusercontent.com/36081235/81972100-1a0d7280-95f0-11ea-830c-4ce86e34b536.png">

Or, probably better, we have it like this:
<img width="398" alt="2" src="https://user-images.githubusercontent.com/36081235/81972799-2514d280-95f1-11ea-9f03-eb395f2fdc68.png">

The second option is better because I think it would be better for users to be able to specify a recurring event on multiple days. (So like lunch you would do M-F). The second way also easily allows us to be able to have the user have a list of history on the event. (I was thinking when you click on the name or perhaps an icon, a list is pulled up similar to the current event list).

It might be a little hard to maintain the stages that we currently have. Take one scenario of having lunch M-F. If the consider time is over 24 hours, then this will cause problems. I think this is workable by just ensuring the validation is solid and that it never allows consider times that will produce such scenarios.

I don't think we should allow recurring events to be edited as that would introduce a lot of unnecessary complexity. Basically if you screw up (like pick the wrong category or forget to add a specific day), then you have to cancel it and re create it.

**Comment by john-andrews12** [comment]
Converted to backlog card in projects
