### ISSUE TITLE
Suggested Choices

### ISSUE THREAD

**Issue by joshrap67** [SCCapstone/decision_maker#572]
Since we want to keep our app as generic as possible, I thought that having suggested choices would be kind of impossible (e.g. what if someone names their "Food" category "F00dz")

What we could do, however, is have a button at the top left of the category edit page where it opens up a suggestion popup. There we can have presets for things like food, movies, bars, games, etc.

**Comment by john-andrews12** [comment]
Converted to backlog card in projects
