### ISSUE TITLE
Ability to request edit permissions of category

### ISSUE THREAD

**Issue by joshrap67** [SCCapstone/decision_maker#574]
Idk this might be too much, I just could imagine one use case of the app would be a group of friends who share a handful of categories. I think it would be annoying to have to text my friend to add a new choice that I just thought of that would be cool for the category.

To make it easy we could just have an option to maybe make categories open or private? Or maybe you have a list of groups it is apart of and can make it private/open on a group basis? Or the harder way where the user has to actually request access and you grant it (I think that's way too involved).

**Comment by john-andrews12** [comment]
Converted to backlog card in projects
